name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Signal R Docker Build
      run: docker build . --file ./src/SignalRApi/Dockerfile --tag my-image-name:$(date +%s)
